# Welcome to Jekyll!

# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
title: Todmorden Aeronautical Space Administration
email: admin@tasa.space
description: >- # this means to ignore newlines until "baseurl:"
  This is the website for the Todmorden Aeronautical Space Administration (TASA), who are going to put a payload into space and take a picture of the character of the Earth and return the payload to earth in 50 days.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tasa.space" 
logo: ../assets/logo.png 
permalink: none
sass:
 sass_dir: _sass
 style: :compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
